---
# System packages (pacman)
system_packages:
  - xorg-server
  - xorg-xinit
  - lightdm
  - lightdm-gtk-greeter
  - i3-wm
  - dmenu
  - i3status
  - i3lock
  - zsh
  - nix
  - vim
  - git
  - curl
  - wget
  - rofi
  - thunar
  - htop
  - sxiv
  - feh
  - lxappearance
  - imagemagick
  - zip
  - unzip
  - jq
  - nitrogen
  - redshift
  - flameshot
  - pulsemixer
  - gnome-calculator
  - bat
  - eza
  - discord
  - ripgrep
  - kubectl
  - podman
  - fzf
  - git-credential-oauth
  - adwaita-icon-theme
  - gnome-themes-extra
  - dmenu
  - i3status
  - i3lock
  - i3blocks
  - cmatrix
  - fastfetch
  - qemu
  - libvirt
  - edk2-ovmf
  - cups
  - bluez
  - bluez-utils
  - networkmanager
  - wpa_supplicant
  - openssh
  - picom
  - alacritty
  - firefox
  - thunderbird
  - code
  - jetbrains-toolbox
  - dejavu-fonts
  - ttf-meslo-nerd
  - noto-fonts
  - linux-firmware
  - vulkan-intel
  - intel-media-driver
  - mesa
  - libva-intel-driver
  - xf86-video-intel

# AUR packages (require yay/paru)
aur_packages:
  - google-chrome
  - spotify
  - bat-extras
